## 1.Create Array

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


## 2. Array Operations

In [ ]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a+b)
print(a*b)

[11 22 33]
[10 40 90]


## 3.Zeros and Ones

In [ ]:
print(np.zeros([2,3]))
print(np.ones([3,3]))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 4.Mean, Max, Min

In [ ]:
data=np.array([10,20,30,40])

print("Mean : ",np.mean(data) )
print("Max  : ", np.max(data) )
print("Min  : ",np.min(data))

Mean :  25.0
Max  :  40
Min  :  10
